### ISSUE TITLE
Make yt fields a tuple to be in line with current yt functionaity

### ISSUE THREAD

**Issue by samwalkow** [data-exp-lab/analysis_schema#30]
### Description

The `field` attribute in the `Fields` dataclass should expect a tuple with the field name and field type and as input.

**Comment by chrishavlin** [comment]
added on to this one -- I think at one point we had multiple fields working for plots but I don't think that works at present. Should be easy to allow passing a list of fields again. I also think the `(field type, field name)` convention **might** be implemented already.... need to double check.
